name: CI Pipeline & Docker Build

on:
  push:
    branches:
      - main

jobs:
  mlops-pipeline:
    runs-on: ubuntu-latest
    env:
      MLFLOW_TRACKING_USERNAME: restuzaki
      MLFLOW_TRACKING_PASSWORD: ${{ secrets.DAGSHUB_TOKEN }}
      MLFLOW_TRACKING_URI: https://dagshub.com/restuzaki/Eksperimen_SML_Damai.mlflow

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install mlflow dagshub pandas scikit-learn

      - name: Train Model
        run: |

          cd Workflow-CI/MLProject
          python modelling.py

      - name: Build and Push Docker Image
        run: |
          cat << 'EOF' > build_script.py
          import mlflow
          import os
          from mlflow.tracking import MlflowClient

          mlflow.set_tracking_uri(os.environ["MLFLOW_TRACKING_URI"])
          client = MlflowClient()


          df = mlflow.search_runs(experiment_names=['Phishing_Detection_CI_Pipeline'], filter_string="status = 'FINISHED'")
          run_id = df.sort_values('start_time', ascending=False).iloc[0].run_id

          print(f"Mengunduh model dari Run: {run_id}")


          client.download_artifacts(run_id=run_id, path="", dst_path='./local_model_dir')
          EOF

          python build_script.py


          mlflow models build-docker -m "./local_model_dir" -n ${{ secrets.DOCKERHUB_USERNAME }}/phishing-model:latest

          docker push ${{ secrets.DOCKERHUB_USERNAME }}/phishing-model:latest
